package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"fmt"
	"strings"
	"time"

	"github.com/pgdepaula/vyst-openauth/internal/domain/company"
	"github.com/pgdepaula/vyst-openauth/internal/domain/event"
	"github.com/pgdepaula/vyst-openauth/internal/domain/tenant"
	"github.com/pgdepaula/vyst-openauth/internal/domain/user"
	graphql1 "github.com/pgdepaula/vyst-openauth/internal/interfaces/graphql"
	"github.com/pgdepaula/vyst-openauth/internal/interfaces/graphql/model"
	"github.com/pgdepaula/vyst-openauth/internal/interfaces/http/middleware"
)

// UpdateUserRoles is the resolver for the updateUserRoles field.
func (r *mutationResolver) UpdateUserRoles(ctx context.Context, userID string, roles []string) (*user.User, error) {
	// TODO: Implement role update logic
	panic(fmt.Errorf("not implemented: UpdateUserRoles"))
}

// DeactivateUser is the resolver for the deactivateUser field.
func (r *mutationResolver) DeactivateUser(ctx context.Context, userID string, reason *string) (*user.User, error) {
	// TODO: Implement user deactivation
	panic(fmt.Errorf("not implemented: DeactivateUser"))
}

// ReactivateUser is the resolver for the reactivateUser field.
func (r *mutationResolver) ReactivateUser(ctx context.Context, userID string) (*user.User, error) {
	// TODO: Implement user reactivation
	panic(fmt.Errorf("not implemented: ReactivateUser"))
}

// UpdateCompanyStatus is the resolver for the updateCompanyStatus field.
func (r *mutationResolver) UpdateCompanyStatus(ctx context.Context, id string, status string) (*model.Company, error) {
	// 1. Get Company
	comp, err := r.CompanyRepo.GetByID(ctx, id)
	if err != nil {
		if err == company.ErrNotFound {
			return nil, fmt.Errorf("company not found")
		}
		return nil, fmt.Errorf("failed to get company: %w", err)
	}

	// 2. Validate and Update Status
	// Lowercase the input status to match domain enum (e.g. SUSPENDED -> suspended)
	st := company.CompanyStatus(strings.ToLower(status))
	if !st.IsValid() {
		return nil, fmt.Errorf("invalid status: %s", status)
	}

	// Update entity
	switch st {
	case company.StatusActive:
		comp.Activate()
	case company.StatusSuspended:
		comp.Suspend()
	case company.StatusPending:
		// Logic for pending? Revert to pending?
		comp.Status = company.StatusPending
		comp.UpdatedAt = time.Now()
	}

	// 3. Persist
	if err := r.CompanyRepo.Update(ctx, comp); err != nil {
		return nil, fmt.Errorf("failed to update company: %w", err)
	}

	return &model.Company{
		ID:           comp.ID,
		TenantID:     comp.TenantID,
		Cnpj:         comp.CNPJ,
		RazaoSocial:  comp.RazaoSocial,
		NomeFantasia: comp.NomeFantasia,
		Status:       string(comp.Status),
		Address: &model.Address{
			Logradouro:  comp.Endereco.Logradouro,
			Numero:      comp.Endereco.Numero,
			Complemento: &comp.Endereco.Complemento,
			Bairro:      comp.Endereco.Bairro,
			Cidade:      comp.Endereco.Cidade,
			Uf:          comp.Endereco.UF,
			Cep:         comp.Endereco.CEP,
		},
		CreatedAt: comp.CreatedAt.Format(time.RFC3339),
		UpdatedAt: comp.UpdatedAt.Format(time.RFC3339),
	}, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*user.User, error) {
	// Get user ID from context (set by auth middleware)
	userID, ok := middleware.UserIDFromContext(ctx)
	if !ok {
		if ctx.Value(middleware.UserIDKey) != nil {
			return nil, fmt.Errorf("invalid user id in context")
		}
		return nil, fmt.Errorf("unauthorized")
	}

	return r.AuthService.GetUser(ctx, userID)
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, filter *model.UserFilterInput, page *int, limit *int) (*model.UserConnection, error) {
	// TODO: Implement user listing with filtering
	// This requires a UserService with ListUsers method
	return &model.UserConnection{
		Items: []*user.User{},
		Count: 0,
	}, nil
}

// Tenants is the resolver for the tenants field.
func (r *queryResolver) Tenants(ctx context.Context, filter *model.TenantFilterInput, page *int, limit *int) (*model.TenantConnection, error) {
	// TODO: Implement tenant listing with filtering
	return &model.TenantConnection{
		Items: []*tenant.Tenant{},
		Count: 0,
	}, nil
}

// Permissions is the resolver for the permissions field.
func (r *queryResolver) Permissions(ctx context.Context) ([]*model.Permission, error) {
	// TODO: Implement permissions listing
	return []*model.Permission{}, nil
}

// Roles is the resolver for the roles field.
func (r *queryResolver) Roles(ctx context.Context) ([]*model.Role, error) {
	// TODO: Implement roles listing via PolicyService
	if r.PolicyRepo == nil {
		return []*model.Role{}, nil
	}
	// Get tenant ID from context for scoped roles
	return []*model.Role{}, nil
}

// Companies is the resolver for the companies field.
func (r *queryResolver) Companies(ctx context.Context, filter *model.CompanyFilterInput, page *int, limit *int) (*model.CompanyConnection, error) {
	// Get user ID from context to filter companies
	userID, ok := middleware.UserIDFromContext(ctx)
	if !ok {
		if ctx.Value(middleware.UserIDKey) != nil {
			return nil, fmt.Errorf("invalid user id in context")
		}
		return nil, fmt.Errorf("unauthorized")
	}

	// Fetch companies for user
	companiesWithRole, err := r.CompanyService.GetCompaniesForUser(ctx, userID)
	if err != nil {
		return nil, fmt.Errorf("failed to list companies: %w", err)
	}

	// Map to GraphQL model
	var items []*model.Company
	for _, c := range companiesWithRole {
		// Filter by status if provided in filter?
		// For now just return all associated companies

		items = append(items, &model.Company{
			ID:           c.Company.ID,
			TenantID:     c.Company.TenantID,
			Cnpj:         c.Company.CNPJ,
			RazaoSocial:  c.Company.RazaoSocial,
			NomeFantasia: c.Company.NomeFantasia,
			Status:       string(c.Company.Status),
			Address: &model.Address{
				Logradouro:  c.Company.Endereco.Logradouro,
				Numero:      c.Company.Endereco.Numero,
				Complemento: &c.Company.Endereco.Complemento,
				Bairro:      c.Company.Endereco.Bairro,
				Cidade:      c.Company.Endereco.Cidade,
				Uf:          c.Company.Endereco.UF,
				Cep:         c.Company.Endereco.CEP,
			},
			CreatedAt: c.Company.CreatedAt.Format(time.RFC3339),
			UpdatedAt: c.Company.UpdatedAt.Format(time.RFC3339),
		})
	}

	// Pagination handling (slice in memory since service returns all)
	// This is temporary until repo supports pagination with user filter
	count := len(items)

	p := 1
	if page != nil && *page > 0 {
		p = *page
	}
	l := 10
	if limit != nil && *limit > 0 {
		l = *limit
	}
	start := (p - 1) * l
	end := start + l

	if start > count {
		start = count
	}
	if end > count {
		end = count
	}

	pagedItems := items[start:end]

	return &model.CompanyConnection{
		Items: pagedItems,
		Count: count,
	}, nil
}

// CompanyInfoCache is the resolver for the companyInfoCache field.
func (r *queryResolver) CompanyInfoCache(ctx context.Context, filter *string, limit *int) ([]*model.CompanyInfoCache, error) {
	if r.CompanyLookupService == nil {
		return nil, fmt.Errorf("company lookup service not configured")
	}

	searchLimit := 10
	if limit != nil && *limit > 0 {
		searchLimit = *limit
	}

	query := ""
	if filter != nil {
		query = *filter
	}

	var results []*company.CompanyInfo
	var err error

	// Try to extract dynamic tenant from context to enforce realistic rate limits
	tenantID, _ := middleware.TenantIDFromContext(ctx)

	results, err = r.CompanyLookupService.Lookup(ctx, tenantID, query, searchLimit)

	if err != nil && err != company.ErrCompanyInfoNotFound {
		return nil, fmt.Errorf("failed to lookup company info: %w", err)
	}

	var parsedResults []*model.CompanyInfoCache
	for _, res := range results {
		var dataAbertura string
		if !res.DataAbertura.IsZero() {
			dataAbertura = res.DataAbertura.Format(time.DateOnly)
		}

		parsedResults = append(parsedResults, &model.CompanyInfoCache{
			Cnpj:             res.CNPJ,
			RazaoSocial:      res.RazaoSocial,
			NomeFantasia:     &res.NomeFantasia,
			Situacao:         string(res.Situacao),
			NaturezaJuridica: &res.NaturezaJuridica,
			DataAbertura:     &dataAbertura,
			Endereco: &model.Address{
				Logradouro:  res.Endereco.Logradouro,
				Numero:      res.Endereco.Numero,
				Complemento: &res.Endereco.Complemento,
				Bairro:      res.Endereco.Bairro,
				Cidade:      res.Endereco.Cidade,
				Uf:          res.Endereco.UF,
				Cep:         res.Endereco.CEP,
			},
			Telefones:     res.Telefones,
			Emails:        res.Emails,
			CnaePrincipal: &res.CNAEPrincipal,
			LastFetchedAt: res.LastFetchedAt.Format(time.RFC3339),
		})
	}

	return parsedResults, nil
}

// CnpjVerifications is the resolver for the cnpjVerifications field.
func (r *queryResolver) CnpjVerifications(ctx context.Context) ([]string, error) {
	return []string{}, nil
}

// UserRegistered is the resolver for the userRegistered field.
func (r *subscriptionResolver) UserRegistered(ctx context.Context) (<-chan *user.User, error) {
	// TODO: Implement WebSocket subscription
	panic(fmt.Errorf("not implemented: UserRegistered"))
}

// UserDeactivated is the resolver for the userDeactivated field.
func (r *subscriptionResolver) UserDeactivated(ctx context.Context) (<-chan *user.User, error) {
	// TODO: Implement WebSocket subscription
	panic(fmt.Errorf("not implemented: UserDeactivated"))
}

// UserRolesUpdated is the resolver for the userRolesUpdated field.
func (r *subscriptionResolver) UserRolesUpdated(ctx context.Context) (<-chan *user.User, error) {
	// TODO: Implement WebSocket subscription
	panic(fmt.Errorf("not implemented: UserRolesUpdated"))
}

// CompanyUserAdded is the resolver for the companyUserAdded field.
func (r *subscriptionResolver) CompanyUserAdded(ctx context.Context, companyID string) (<-chan *model.CompanyUser, error) {
	ch := make(chan *model.CompanyUser, 1)

	handler := func(ctx context.Context, e event.Event) error {
		payload, ok := e.Payload.(event.CompanyUserAddedPayload)
		if !ok {
			// Try to cast from map if coming from JSON
			// In in-memory bus it preserves type if passed as struct, but good to be safe if serialized
			// Here assuming struct preservation or we need better unmarshaling
			return nil
		}

		if payload.CompanyID != companyID {
			return nil
		}

		modelUser := &model.CompanyUser{
			CompanyID: payload.CompanyID,
			UserID:    payload.UserID,
			Role:      payload.Role,
			Status:    "active", // Default status for added user
			JoinedAt:  time.Now().Format(time.RFC3339),
		}

		// Non-blocking send
		select {
		case ch <- modelUser:
		default:
			// Client likely disconnected or slow
		}
		return nil
	}

	unsubscribe := r.EventBus.Subscribe(event.CompanyUserAdded, handler)

	// Clean up when context is done
	go func() {
		<-ctx.Done()
		unsubscribe()
	}()

	return ch, nil
}

// Status is the resolver for the status field.
func (r *tenantResolver) Status(ctx context.Context, obj *tenant.Tenant) (string, error) {
	return string(obj.Status), nil
}

// UserCount is the resolver for the user_count field.
func (r *tenantResolver) UserCount(ctx context.Context, obj *tenant.Tenant) (int, error) {
	// TODO: Implement user count
	return 0, nil
}

// CreatedAt is the resolver for the created_at field.
func (r *tenantResolver) CreatedAt(ctx context.Context, obj *tenant.Tenant) (string, error) {
	return obj.CreatedAt.Format(time.RFC3339), nil
}

// UpdatedAt is the resolver for the updated_at field.
func (r *tenantResolver) UpdatedAt(ctx context.Context, obj *tenant.Tenant) (string, error) {
	return obj.UpdatedAt.Format(time.RFC3339), nil
}

// Roles is the resolver for the roles field in User type.
func (r *userResolver) Roles(ctx context.Context, obj *user.User) ([]string, error) {
	// For now return empty roles - will be populated by policy service
	return []string{}, nil
}

// CreatedAt is the resolver for the created_at field.
func (r *userResolver) CreatedAt(ctx context.Context, obj *user.User) (string, error) {
	return obj.CreatedAt.Format(time.RFC3339), nil
}

// UpdatedAt is the resolver for the updated_at field.
func (r *userResolver) UpdatedAt(ctx context.Context, obj *user.User) (string, error) {
	return obj.UpdatedAt.Format(time.RFC3339), nil
}

// Mutation returns graphql1.MutationResolver implementation.
func (r *Resolver) Mutation() graphql1.MutationResolver { return &mutationResolver{r} }

// Query returns graphql1.QueryResolver implementation.
func (r *Resolver) Query() graphql1.QueryResolver { return &queryResolver{r} }

// Subscription returns graphql1.SubscriptionResolver implementation.
func (r *Resolver) Subscription() graphql1.SubscriptionResolver { return &subscriptionResolver{r} }

// Tenant returns graphql1.TenantResolver implementation.
func (r *Resolver) Tenant() graphql1.TenantResolver { return &tenantResolver{r} }

// User returns graphql1.UserResolver implementation.
func (r *Resolver) User() graphql1.UserResolver { return &userResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
type tenantResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
