// Package openapi contains Swagger documentation for the Vyst Identity API.
// This file provides the main API information annotations for swag init.
//
//	@title						Vyst Identity API
//	@version					1.0
//	@description				Enterprise-grade Identity and Access Management API
//	@termsOfService				https://vyst.io/terms
//	@contact.name				Vyst Support
//	@contact.email				pedro@depaula.tech
//	@license.name				Proprietary
//	@host						localhost:8080
//	@BasePath					/
//	@securityDefinitions.apikey	BearerAuth
//	@in							header
//	@name						Authorization
//	@description				JWT Bearer token. Format: "Bearer {token}"
package rest

// This file is intentionally kept minimal.
// The actual documentation is generated by running:
//   swag init -g cmd/identity-api/main.go -o api/openapi
