apiVersion: v1
kind: Pod
metadata:
  name: identity-pod
spec:
  containers:
  - name: identity
    image: vyst/identity:latest
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 3
      periodSeconds: 3
    readinessProbe:
      httpGet:
        path: /ready
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5
