// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: api/proto/identity.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IdentityService_ValidateToken_FullMethodName         = "/identity.IdentityService/ValidateToken"
	IdentityService_StreamValidateSession_FullMethodName = "/identity.IdentityService/StreamValidateSession"
	IdentityService_GetUserRoles_FullMethodName          = "/identity.IdentityService/GetUserRoles"
	IdentityService_GetUserPermissions_FullMethodName    = "/identity.IdentityService/GetUserPermissions"
	IdentityService_RevokeUserSessions_FullMethodName    = "/identity.IdentityService/RevokeUserSessions"
	IdentityService_ValidateCompanyAccess_FullMethodName = "/identity.IdentityService/ValidateCompanyAccess"
	IdentityService_GetCompanyRoles_FullMethodName       = "/identity.IdentityService/GetCompanyRoles"
)

// IdentityServiceClient is the client API for IdentityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// IdentityService provides authorization and identity validation operations.
// All methods are optimized for high-performance, real-time S2S communication.
type IdentityServiceClient interface {
	// ValidateToken validates a JWT access token.
	// Used by downstream services to verify authentication.
	// Optimized for stateless RSA signature verification.
	//
	// Error codes:
	// - UNAUTHENTICATED: Token is invalid or expired
	ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*ValidateTokenResponse, error)
	// StreamValidateSession provides real-time session validation.
	// Used for implementing security kill switches and session monitoring.
	// The server will push updates when session status changes.
	StreamValidateSession(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ValidateSessionRequest, ValidateSessionResponse], error)
	// GetUserRoles returns the roles assigned to a user.
	// Used by backend services for authorization decisions.
	//
	// Error codes:
	// - NOT_FOUND: User or tenant not found
	// - UNAUTHENTICATED: Invalid token in metadata
	GetUserRoles(ctx context.Context, in *GetUserRolesRequest, opts ...grpc.CallOption) (*GetUserRolesResponse, error)
	// GetUserPermissions returns the full permission set for a user.
	// Aggregates permissions from all user roles.
	//
	// Error codes:
	// - NOT_FOUND: User not found
	// - UNAUTHENTICATED: Invalid token in metadata
	GetUserPermissions(ctx context.Context, in *GetUserPermissionsRequest, opts ...grpc.CallOption) (*GetUserPermissionsResponse, error)
	// RevokeUserSessions terminates all active sessions for a user.
	// Triggers the Kill Switch mechanism across all connected services.
	//
	// Error codes:
	// - NOT_FOUND: User not found
	// - PERMISSION_DENIED: Caller lacks admin privileges
	// RevokeUserSessions terminates all active sessions for a user.
	// Triggers the Kill Switch mechanism across all connected services.
	//
	// Error codes:
	// - NOT_FOUND: User not found
	// - PERMISSION_DENIED: Caller lacks admin privileges
	RevokeUserSessions(ctx context.Context, in *RevokeUserSessionsRequest, opts ...grpc.CallOption) (*RevokeUserSessionsResponse, error)
	// ValidateCompanyAccess checks if a user (via token) has access to a specific company.
	// Returns the user's role in the company.
	ValidateCompanyAccess(ctx context.Context, in *ValidateCompanyAccessRequest, opts ...grpc.CallOption) (*ValidateCompanyAccessResponse, error)
	// GetCompanyRoles returns all company memberships for a user.
	GetCompanyRoles(ctx context.Context, in *GetCompanyRolesRequest, opts ...grpc.CallOption) (*GetCompanyRolesResponse, error)
}

type identityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIdentityServiceClient(cc grpc.ClientConnInterface) IdentityServiceClient {
	return &identityServiceClient{cc}
}

func (c *identityServiceClient) ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*ValidateTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateTokenResponse)
	err := c.cc.Invoke(ctx, IdentityService_ValidateToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) StreamValidateSession(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ValidateSessionRequest, ValidateSessionResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &IdentityService_ServiceDesc.Streams[0], IdentityService_StreamValidateSession_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ValidateSessionRequest, ValidateSessionResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IdentityService_StreamValidateSessionClient = grpc.BidiStreamingClient[ValidateSessionRequest, ValidateSessionResponse]

func (c *identityServiceClient) GetUserRoles(ctx context.Context, in *GetUserRolesRequest, opts ...grpc.CallOption) (*GetUserRolesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserRolesResponse)
	err := c.cc.Invoke(ctx, IdentityService_GetUserRoles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) GetUserPermissions(ctx context.Context, in *GetUserPermissionsRequest, opts ...grpc.CallOption) (*GetUserPermissionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserPermissionsResponse)
	err := c.cc.Invoke(ctx, IdentityService_GetUserPermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) RevokeUserSessions(ctx context.Context, in *RevokeUserSessionsRequest, opts ...grpc.CallOption) (*RevokeUserSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeUserSessionsResponse)
	err := c.cc.Invoke(ctx, IdentityService_RevokeUserSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) ValidateCompanyAccess(ctx context.Context, in *ValidateCompanyAccessRequest, opts ...grpc.CallOption) (*ValidateCompanyAccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateCompanyAccessResponse)
	err := c.cc.Invoke(ctx, IdentityService_ValidateCompanyAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) GetCompanyRoles(ctx context.Context, in *GetCompanyRolesRequest, opts ...grpc.CallOption) (*GetCompanyRolesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCompanyRolesResponse)
	err := c.cc.Invoke(ctx, IdentityService_GetCompanyRoles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentityServiceServer is the server API for IdentityService service.
// All implementations must embed UnimplementedIdentityServiceServer
// for forward compatibility.
//
// IdentityService provides authorization and identity validation operations.
// All methods are optimized for high-performance, real-time S2S communication.
type IdentityServiceServer interface {
	// ValidateToken validates a JWT access token.
	// Used by downstream services to verify authentication.
	// Optimized for stateless RSA signature verification.
	//
	// Error codes:
	// - UNAUTHENTICATED: Token is invalid or expired
	ValidateToken(context.Context, *ValidateTokenRequest) (*ValidateTokenResponse, error)
	// StreamValidateSession provides real-time session validation.
	// Used for implementing security kill switches and session monitoring.
	// The server will push updates when session status changes.
	StreamValidateSession(grpc.BidiStreamingServer[ValidateSessionRequest, ValidateSessionResponse]) error
	// GetUserRoles returns the roles assigned to a user.
	// Used by backend services for authorization decisions.
	//
	// Error codes:
	// - NOT_FOUND: User or tenant not found
	// - UNAUTHENTICATED: Invalid token in metadata
	GetUserRoles(context.Context, *GetUserRolesRequest) (*GetUserRolesResponse, error)
	// GetUserPermissions returns the full permission set for a user.
	// Aggregates permissions from all user roles.
	//
	// Error codes:
	// - NOT_FOUND: User not found
	// - UNAUTHENTICATED: Invalid token in metadata
	GetUserPermissions(context.Context, *GetUserPermissionsRequest) (*GetUserPermissionsResponse, error)
	// RevokeUserSessions terminates all active sessions for a user.
	// Triggers the Kill Switch mechanism across all connected services.
	//
	// Error codes:
	// - NOT_FOUND: User not found
	// - PERMISSION_DENIED: Caller lacks admin privileges
	// RevokeUserSessions terminates all active sessions for a user.
	// Triggers the Kill Switch mechanism across all connected services.
	//
	// Error codes:
	// - NOT_FOUND: User not found
	// - PERMISSION_DENIED: Caller lacks admin privileges
	RevokeUserSessions(context.Context, *RevokeUserSessionsRequest) (*RevokeUserSessionsResponse, error)
	// ValidateCompanyAccess checks if a user (via token) has access to a specific company.
	// Returns the user's role in the company.
	ValidateCompanyAccess(context.Context, *ValidateCompanyAccessRequest) (*ValidateCompanyAccessResponse, error)
	// GetCompanyRoles returns all company memberships for a user.
	GetCompanyRoles(context.Context, *GetCompanyRolesRequest) (*GetCompanyRolesResponse, error)
	mustEmbedUnimplementedIdentityServiceServer()
}

// UnimplementedIdentityServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIdentityServiceServer struct{}

func (UnimplementedIdentityServiceServer) ValidateToken(context.Context, *ValidateTokenRequest) (*ValidateTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateToken not implemented")
}
func (UnimplementedIdentityServiceServer) StreamValidateSession(grpc.BidiStreamingServer[ValidateSessionRequest, ValidateSessionResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamValidateSession not implemented")
}
func (UnimplementedIdentityServiceServer) GetUserRoles(context.Context, *GetUserRolesRequest) (*GetUserRolesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserRoles not implemented")
}
func (UnimplementedIdentityServiceServer) GetUserPermissions(context.Context, *GetUserPermissionsRequest) (*GetUserPermissionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserPermissions not implemented")
}
func (UnimplementedIdentityServiceServer) RevokeUserSessions(context.Context, *RevokeUserSessionsRequest) (*RevokeUserSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeUserSessions not implemented")
}
func (UnimplementedIdentityServiceServer) ValidateCompanyAccess(context.Context, *ValidateCompanyAccessRequest) (*ValidateCompanyAccessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateCompanyAccess not implemented")
}
func (UnimplementedIdentityServiceServer) GetCompanyRoles(context.Context, *GetCompanyRolesRequest) (*GetCompanyRolesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCompanyRoles not implemented")
}
func (UnimplementedIdentityServiceServer) mustEmbedUnimplementedIdentityServiceServer() {}
func (UnimplementedIdentityServiceServer) testEmbeddedByValue()                         {}

// UnsafeIdentityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdentityServiceServer will
// result in compilation errors.
type UnsafeIdentityServiceServer interface {
	mustEmbedUnimplementedIdentityServiceServer()
}

func RegisterIdentityServiceServer(s grpc.ServiceRegistrar, srv IdentityServiceServer) {
	// If the following call panics, it indicates UnimplementedIdentityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IdentityService_ServiceDesc, srv)
}

func _IdentityService_ValidateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).ValidateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_ValidateToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).ValidateToken(ctx, req.(*ValidateTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_StreamValidateSession_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IdentityServiceServer).StreamValidateSession(&grpc.GenericServerStream[ValidateSessionRequest, ValidateSessionResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IdentityService_StreamValidateSessionServer = grpc.BidiStreamingServer[ValidateSessionRequest, ValidateSessionResponse]

func _IdentityService_GetUserRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRolesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).GetUserRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_GetUserRoles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).GetUserRoles(ctx, req.(*GetUserRolesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_GetUserPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserPermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).GetUserPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_GetUserPermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).GetUserPermissions(ctx, req.(*GetUserPermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_RevokeUserSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeUserSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).RevokeUserSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_RevokeUserSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).RevokeUserSessions(ctx, req.(*RevokeUserSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_ValidateCompanyAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateCompanyAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).ValidateCompanyAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_ValidateCompanyAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).ValidateCompanyAccess(ctx, req.(*ValidateCompanyAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_GetCompanyRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCompanyRolesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).GetCompanyRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_GetCompanyRoles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).GetCompanyRoles(ctx, req.(*GetCompanyRolesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IdentityService_ServiceDesc is the grpc.ServiceDesc for IdentityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IdentityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "identity.IdentityService",
	HandlerType: (*IdentityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidateToken",
			Handler:    _IdentityService_ValidateToken_Handler,
		},
		{
			MethodName: "GetUserRoles",
			Handler:    _IdentityService_GetUserRoles_Handler,
		},
		{
			MethodName: "GetUserPermissions",
			Handler:    _IdentityService_GetUserPermissions_Handler,
		},
		{
			MethodName: "RevokeUserSessions",
			Handler:    _IdentityService_RevokeUserSessions_Handler,
		},
		{
			MethodName: "ValidateCompanyAccess",
			Handler:    _IdentityService_ValidateCompanyAccess_Handler,
		},
		{
			MethodName: "GetCompanyRoles",
			Handler:    _IdentityService_GetCompanyRoles_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamValidateSession",
			Handler:       _IdentityService_StreamValidateSession_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/proto/identity.proto",
}
