// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: api/proto/identity.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ValidateTokenRequest contains the token to validate.
type ValidateTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JWT access token to validate
	Token         string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenRequest) Reset() {
	*x = ValidateTokenRequest{}
	mi := &file_api_proto_identity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenRequest) ProtoMessage() {}

func (x *ValidateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_identity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenRequest.ProtoReflect.Descriptor instead.
func (*ValidateTokenRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_identity_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// ValidateTokenResponse contains the validation result and user info.
type ValidateTokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the token is valid
	Valid bool `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	// User ID from the token claims
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Tenant ID from the token claims
	TenantId string `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// User's roles from the token claims
	Roles         []string `protobuf:"bytes,4,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenResponse) Reset() {
	*x = ValidateTokenResponse{}
	mi := &file_api_proto_identity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenResponse) ProtoMessage() {}

func (x *ValidateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_identity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenResponse.ProtoReflect.Descriptor instead.
func (*ValidateTokenResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_identity_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateTokenResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateTokenResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ValidateTokenResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ValidateTokenResponse) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

// ValidateSessionRequest is used for streaming session validation.
type ValidateSessionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Session ID or token to monitor
	SessionId     string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateSessionRequest) Reset() {
	*x = ValidateSessionRequest{}
	mi := &file_api_proto_identity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateSessionRequest) ProtoMessage() {}

func (x *ValidateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_identity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateSessionRequest.ProtoReflect.Descriptor instead.
func (*ValidateSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_identity_proto_rawDescGZIP(), []int{2}
}

func (x *ValidateSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// ValidateSessionResponse contains the session status.
type ValidateSessionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the session is still active
	Active bool `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	// Reason for session invalidation (if not active)
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateSessionResponse) Reset() {
	*x = ValidateSessionResponse{}
	mi := &file_api_proto_identity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateSessionResponse) ProtoMessage() {}

func (x *ValidateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_identity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateSessionResponse.ProtoReflect.Descriptor instead.
func (*ValidateSessionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_identity_proto_rawDescGZIP(), []int{3}
}

func (x *ValidateSessionResponse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *ValidateSessionResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// GetUserRolesRequest specifies the user to query roles for.
type GetUserRolesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User ID to get roles for
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Tenant ID for tenant-scoped roles
	TenantId      string `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRolesRequest) Reset() {
	*x = GetUserRolesRequest{}
	mi := &file_api_proto_identity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRolesRequest) ProtoMessage() {}

func (x *GetUserRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_identity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRolesRequest.ProtoReflect.Descriptor instead.
func (*GetUserRolesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_identity_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserRolesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserRolesRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

// GetUserRolesResponse contains the user's assigned roles.
type GetUserRolesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of role names assigned to the user
	Roles         []string `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRolesResponse) Reset() {
	*x = GetUserRolesResponse{}
	mi := &file_api_proto_identity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRolesResponse) ProtoMessage() {}

func (x *GetUserRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_identity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRolesResponse.ProtoReflect.Descriptor instead.
func (*GetUserRolesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_identity_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserRolesResponse) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

// GetUserPermissionsRequest specifies the user to query permissions for.
type GetUserPermissionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User ID to get permissions for
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Tenant ID for tenant-scoped permissions
	TenantId      string `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPermissionsRequest) Reset() {
	*x = GetUserPermissionsRequest{}
	mi := &file_api_proto_identity_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPermissionsRequest) ProtoMessage() {}

func (x *GetUserPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_identity_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPermissionsRequest.ProtoReflect.Descriptor instead.
func (*GetUserPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_identity_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserPermissionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserPermissionsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

// Permission represents a single permission entry.
type Permission struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resource type (e.g., "invoice", "user", "report")
	Resource string `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	// Action allowed (e.g., "read", "write", "delete")
	Action string `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	// Optional: specific resource ID or "*" for all
	ResourceId    string `protobuf:"bytes,3,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Permission) Reset() {
	*x = Permission{}
	mi := &file_api_proto_identity_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Permission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Permission) ProtoMessage() {}

func (x *Permission) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_identity_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Permission.ProtoReflect.Descriptor instead.
func (*Permission) Descriptor() ([]byte, []int) {
	return file_api_proto_identity_proto_rawDescGZIP(), []int{7}
}

func (x *Permission) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *Permission) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *Permission) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

// GetUserPermissionsResponse contains the user's full permission set.
type GetUserPermissionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of permissions the user has
	Permissions   []*Permission `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPermissionsResponse) Reset() {
	*x = GetUserPermissionsResponse{}
	mi := &file_api_proto_identity_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPermissionsResponse) ProtoMessage() {}

func (x *GetUserPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_identity_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPermissionsResponse.ProtoReflect.Descriptor instead.
func (*GetUserPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_identity_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserPermissionsResponse) GetPermissions() []*Permission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

// RevokeUserSessionsRequest specifies the user whose sessions to revoke.
type RevokeUserSessionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User ID whose sessions should be revoked
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Reason for revocation (logged for audit)
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeUserSessionsRequest) Reset() {
	*x = RevokeUserSessionsRequest{}
	mi := &file_api_proto_identity_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeUserSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeUserSessionsRequest) ProtoMessage() {}

func (x *RevokeUserSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_identity_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeUserSessionsRequest.ProtoReflect.Descriptor instead.
func (*RevokeUserSessionsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_identity_proto_rawDescGZIP(), []int{9}
}

func (x *RevokeUserSessionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RevokeUserSessionsRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// RevokeUserSessionsResponse indicates the result of session revocation.
type RevokeUserSessionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of sessions that were revoked
	RevokedCount int32 `protobuf:"varint,1,opt,name=revoked_count,json=revokedCount,proto3" json:"revoked_count,omitempty"`
	// Whether the operation was successful
	Success       bool `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeUserSessionsResponse) Reset() {
	*x = RevokeUserSessionsResponse{}
	mi := &file_api_proto_identity_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeUserSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeUserSessionsResponse) ProtoMessage() {}

func (x *RevokeUserSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_identity_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeUserSessionsResponse.ProtoReflect.Descriptor instead.
func (*RevokeUserSessionsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_identity_proto_rawDescGZIP(), []int{10}
}

func (x *RevokeUserSessionsResponse) GetRevokedCount() int32 {
	if x != nil {
		return x.RevokedCount
	}
	return 0
}

func (x *RevokeUserSessionsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ValidateCompanyAccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	CompanyId     string                 `protobuf:"bytes,2,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateCompanyAccessRequest) Reset() {
	*x = ValidateCompanyAccessRequest{}
	mi := &file_api_proto_identity_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateCompanyAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateCompanyAccessRequest) ProtoMessage() {}

func (x *ValidateCompanyAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_identity_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateCompanyAccessRequest.ProtoReflect.Descriptor instead.
func (*ValidateCompanyAccessRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_identity_proto_rawDescGZIP(), []int{11}
}

func (x *ValidateCompanyAccessRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ValidateCompanyAccessRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

type ValidateCompanyAccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"` // Role in the company (admin, member, viewer)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateCompanyAccessResponse) Reset() {
	*x = ValidateCompanyAccessResponse{}
	mi := &file_api_proto_identity_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateCompanyAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateCompanyAccessResponse) ProtoMessage() {}

func (x *ValidateCompanyAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_identity_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateCompanyAccessResponse.ProtoReflect.Descriptor instead.
func (*ValidateCompanyAccessResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_identity_proto_rawDescGZIP(), []int{12}
}

func (x *ValidateCompanyAccessResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateCompanyAccessResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ValidateCompanyAccessResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type GetCompanyRolesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompanyRolesRequest) Reset() {
	*x = GetCompanyRolesRequest{}
	mi := &file_api_proto_identity_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompanyRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompanyRolesRequest) ProtoMessage() {}

func (x *GetCompanyRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_identity_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompanyRolesRequest.ProtoReflect.Descriptor instead.
func (*GetCompanyRolesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_identity_proto_rawDescGZIP(), []int{13}
}

func (x *GetCompanyRolesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CompanyRoleEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CompanyId     string                 `protobuf:"bytes,1,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompanyRoleEntry) Reset() {
	*x = CompanyRoleEntry{}
	mi := &file_api_proto_identity_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompanyRoleEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompanyRoleEntry) ProtoMessage() {}

func (x *CompanyRoleEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_identity_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompanyRoleEntry.ProtoReflect.Descriptor instead.
func (*CompanyRoleEntry) Descriptor() ([]byte, []int) {
	return file_api_proto_identity_proto_rawDescGZIP(), []int{14}
}

func (x *CompanyRoleEntry) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *CompanyRoleEntry) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type GetCompanyRolesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roles         []*CompanyRoleEntry    `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompanyRolesResponse) Reset() {
	*x = GetCompanyRolesResponse{}
	mi := &file_api_proto_identity_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompanyRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompanyRolesResponse) ProtoMessage() {}

func (x *GetCompanyRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_identity_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompanyRolesResponse.ProtoReflect.Descriptor instead.
func (*GetCompanyRolesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_identity_proto_rawDescGZIP(), []int{15}
}

func (x *GetCompanyRolesResponse) GetRoles() []*CompanyRoleEntry {
	if x != nil {
		return x.Roles
	}
	return nil
}

var File_api_proto_identity_proto protoreflect.FileDescriptor

const file_api_proto_identity_proto_rawDesc = "" +
	"\n" +
	"\x18api/proto/identity.proto\x12\bidentity\",\n" +
	"\x14ValidateTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"y\n" +
	"\x15ValidateTokenResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12\x14\n" +
	"\x05roles\x18\x04 \x03(\tR\x05roles\"7\n" +
	"\x16ValidateSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"I\n" +
	"\x17ValidateSessionResponse\x12\x16\n" +
	"\x06active\x18\x01 \x01(\bR\x06active\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"K\n" +
	"\x13GetUserRolesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\",\n" +
	"\x14GetUserRolesResponse\x12\x14\n" +
	"\x05roles\x18\x01 \x03(\tR\x05roles\"Q\n" +
	"\x19GetUserPermissionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\"a\n" +
	"\n" +
	"Permission\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x1f\n" +
	"\vresource_id\x18\x03 \x01(\tR\n" +
	"resourceId\"T\n" +
	"\x1aGetUserPermissionsResponse\x126\n" +
	"\vpermissions\x18\x01 \x03(\v2\x14.identity.PermissionR\vpermissions\"L\n" +
	"\x19RevokeUserSessionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"[\n" +
	"\x1aRevokeUserSessionsResponse\x12#\n" +
	"\rrevoked_count\x18\x01 \x01(\x05R\frevokedCount\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"S\n" +
	"\x1cValidateCompanyAccessRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"company_id\x18\x02 \x01(\tR\tcompanyId\"b\n" +
	"\x1dValidateCompanyAccessResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\"1\n" +
	"\x16GetCompanyRolesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"E\n" +
	"\x10CompanyRoleEntry\x12\x1d\n" +
	"\n" +
	"company_id\x18\x01 \x01(\tR\tcompanyId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\"K\n" +
	"\x17GetCompanyRolesResponse\x120\n" +
	"\x05roles\x18\x01 \x03(\v2\x1a.identity.CompanyRoleEntryR\x05roles2\x98\x05\n" +
	"\x0fIdentityService\x12P\n" +
	"\rValidateToken\x12\x1e.identity.ValidateTokenRequest\x1a\x1f.identity.ValidateTokenResponse\x12`\n" +
	"\x15StreamValidateSession\x12 .identity.ValidateSessionRequest\x1a!.identity.ValidateSessionResponse(\x010\x01\x12M\n" +
	"\fGetUserRoles\x12\x1d.identity.GetUserRolesRequest\x1a\x1e.identity.GetUserRolesResponse\x12_\n" +
	"\x12GetUserPermissions\x12#.identity.GetUserPermissionsRequest\x1a$.identity.GetUserPermissionsResponse\x12_\n" +
	"\x12RevokeUserSessions\x12#.identity.RevokeUserSessionsRequest\x1a$.identity.RevokeUserSessionsResponse\x12h\n" +
	"\x15ValidateCompanyAccess\x12&.identity.ValidateCompanyAccessRequest\x1a'.identity.ValidateCompanyAccessResponse\x12V\n" +
	"\x0fGetCompanyRoles\x12 .identity.GetCompanyRolesRequest\x1a!.identity.GetCompanyRolesResponseB$Z\"github.com/vyst/identity/api/protob\x06proto3"

var (
	file_api_proto_identity_proto_rawDescOnce sync.Once
	file_api_proto_identity_proto_rawDescData []byte
)

func file_api_proto_identity_proto_rawDescGZIP() []byte {
	file_api_proto_identity_proto_rawDescOnce.Do(func() {
		file_api_proto_identity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_identity_proto_rawDesc), len(file_api_proto_identity_proto_rawDesc)))
	})
	return file_api_proto_identity_proto_rawDescData
}

var file_api_proto_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_api_proto_identity_proto_goTypes = []any{
	(*ValidateTokenRequest)(nil),          // 0: identity.ValidateTokenRequest
	(*ValidateTokenResponse)(nil),         // 1: identity.ValidateTokenResponse
	(*ValidateSessionRequest)(nil),        // 2: identity.ValidateSessionRequest
	(*ValidateSessionResponse)(nil),       // 3: identity.ValidateSessionResponse
	(*GetUserRolesRequest)(nil),           // 4: identity.GetUserRolesRequest
	(*GetUserRolesResponse)(nil),          // 5: identity.GetUserRolesResponse
	(*GetUserPermissionsRequest)(nil),     // 6: identity.GetUserPermissionsRequest
	(*Permission)(nil),                    // 7: identity.Permission
	(*GetUserPermissionsResponse)(nil),    // 8: identity.GetUserPermissionsResponse
	(*RevokeUserSessionsRequest)(nil),     // 9: identity.RevokeUserSessionsRequest
	(*RevokeUserSessionsResponse)(nil),    // 10: identity.RevokeUserSessionsResponse
	(*ValidateCompanyAccessRequest)(nil),  // 11: identity.ValidateCompanyAccessRequest
	(*ValidateCompanyAccessResponse)(nil), // 12: identity.ValidateCompanyAccessResponse
	(*GetCompanyRolesRequest)(nil),        // 13: identity.GetCompanyRolesRequest
	(*CompanyRoleEntry)(nil),              // 14: identity.CompanyRoleEntry
	(*GetCompanyRolesResponse)(nil),       // 15: identity.GetCompanyRolesResponse
}
var file_api_proto_identity_proto_depIdxs = []int32{
	7,  // 0: identity.GetUserPermissionsResponse.permissions:type_name -> identity.Permission
	14, // 1: identity.GetCompanyRolesResponse.roles:type_name -> identity.CompanyRoleEntry
	0,  // 2: identity.IdentityService.ValidateToken:input_type -> identity.ValidateTokenRequest
	2,  // 3: identity.IdentityService.StreamValidateSession:input_type -> identity.ValidateSessionRequest
	4,  // 4: identity.IdentityService.GetUserRoles:input_type -> identity.GetUserRolesRequest
	6,  // 5: identity.IdentityService.GetUserPermissions:input_type -> identity.GetUserPermissionsRequest
	9,  // 6: identity.IdentityService.RevokeUserSessions:input_type -> identity.RevokeUserSessionsRequest
	11, // 7: identity.IdentityService.ValidateCompanyAccess:input_type -> identity.ValidateCompanyAccessRequest
	13, // 8: identity.IdentityService.GetCompanyRoles:input_type -> identity.GetCompanyRolesRequest
	1,  // 9: identity.IdentityService.ValidateToken:output_type -> identity.ValidateTokenResponse
	3,  // 10: identity.IdentityService.StreamValidateSession:output_type -> identity.ValidateSessionResponse
	5,  // 11: identity.IdentityService.GetUserRoles:output_type -> identity.GetUserRolesResponse
	8,  // 12: identity.IdentityService.GetUserPermissions:output_type -> identity.GetUserPermissionsResponse
	10, // 13: identity.IdentityService.RevokeUserSessions:output_type -> identity.RevokeUserSessionsResponse
	12, // 14: identity.IdentityService.ValidateCompanyAccess:output_type -> identity.ValidateCompanyAccessResponse
	15, // 15: identity.IdentityService.GetCompanyRoles:output_type -> identity.GetCompanyRolesResponse
	9,  // [9:16] is the sub-list for method output_type
	2,  // [2:9] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_identity_proto_init() }
func file_api_proto_identity_proto_init() {
	if File_api_proto_identity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_identity_proto_rawDesc), len(file_api_proto_identity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_identity_proto_goTypes,
		DependencyIndexes: file_api_proto_identity_proto_depIdxs,
		MessageInfos:      file_api_proto_identity_proto_msgTypes,
	}.Build()
	File_api_proto_identity_proto = out.File
	file_api_proto_identity_proto_goTypes = nil
	file_api_proto_identity_proto_depIdxs = nil
}
