// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/pgdepaula/vyst-openauth/internal/domain/tenant"
	"github.com/pgdepaula/vyst-openauth/internal/domain/user"
)

// Address represents a physical location.
type Address struct {
	Logradouro  string  `json:"logradouro"`
	Numero      string  `json:"numero"`
	Complemento *string `json:"complemento,omitempty"`
	Bairro      string  `json:"bairro"`
	Cidade      string  `json:"cidade"`
	Uf          string  `json:"uf"`
	Cep         string  `json:"cep"`
}

// Company represents a legal entity (pessoa jurídica).
type Company struct {
	// Unique company identifier (UUID)
	ID string `json:"id"`
	// Tenant this company belongs to
	TenantID string `json:"tenant_id"`
	// CNPJ (14 digits)
	Cnpj string `json:"cnpj"`
	// Legal name (Razão Social)
	RazaoSocial string `json:"razao_social"`
	// Trade name (Nome Fantasia)
	NomeFantasia string `json:"nome_fantasia"`
	// Company status: active, pending, suspended
	Status string `json:"status"`
	// Company address
	Address *Address `json:"address"`
	// ISO 8601 creation timestamp
	CreatedAt string `json:"created_at"`
	// ISO 8601 last update timestamp
	UpdatedAt string `json:"updated_at"`
}

// CompanyConnection represents a paginated list of companies.
type CompanyConnection struct {
	Items []*Company `json:"items"`
	Count int        `json:"count"`
}

// CompanyFilterInput allows filtering companies.
type CompanyFilterInput struct {
	Status     *string `json:"status,omitempty"`
	Cnpj       *string `json:"cnpj,omitempty"`
	NameSearch *string `json:"nameSearch,omitempty"`
}

// CompanyInfoCache represents the enriched company data from external APIs.
type CompanyInfoCache struct {
	Cnpj             string   `json:"cnpj"`
	RazaoSocial      string   `json:"razao_social"`
	NomeFantasia     *string  `json:"nome_fantasia,omitempty"`
	Situacao         string   `json:"situacao"`
	NaturezaJuridica *string  `json:"natureza_juridica,omitempty"`
	DataAbertura     *string  `json:"data_abertura,omitempty"`
	Endereco         *Address `json:"endereco"`
	Telefones        []string `json:"telefones,omitempty"`
	Emails           []string `json:"emails,omitempty"`
	CnaePrincipal    *string  `json:"cnae_principal,omitempty"`
	LastFetchedAt    string   `json:"last_fetched_at"`
}

// CompanyUser represents a user's membership in a company.
type CompanyUser struct {
	CompanyID string `json:"company_id"`
	UserID    string `json:"user_id"`
	Role      string `json:"role"`
	Status    string `json:"status"`
	JoinedAt  string `json:"joined_at"`
}

// Mutation operations. Auth is via REST API, these are admin operations.
type Mutation struct {
}

// Permission represents an access control entry.
type Permission struct {
	// Unique permission identifier
	ID string `json:"id"`
	// Resource type (e.g., invoice, user, report)
	Resource string `json:"resource"`
	// Allowed action (e.g., read, write, delete)
	Action string `json:"action"`
	// Permission description
	Description string `json:"description"`
}

// Query operations for reading data. Requires authentication.
type Query struct {
}

// Role represents a named set of permissions.
type Role struct {
	// Unique role identifier
	ID string `json:"id"`
	// Role name (e.g., admin, viewer, editor)
	Name string `json:"name"`
	// Role description
	Description string `json:"description"`
	// Permissions granted by this role
	Permissions []*Permission `json:"permissions"`
}

// Subscription operations for real-time admin dashboard updates.
type Subscription struct {
}

// TenantConnection represents a paginated list of tenants.
type TenantConnection struct {
	// List of tenants in this page
	Items []*tenant.Tenant `json:"items"`
	// Total count of tenants matching the filter
	Count int `json:"count"`
}

// TenantFilterInput allows filtering tenants by various criteria.
type TenantFilterInput struct {
	// Filter by status (active, suspended)
	Status *string `json:"status,omitempty"`
	// Search by tenant name (partial match)
	NameSearch *string `json:"nameSearch,omitempty"`
	// Filter tenants created after this ISO 8601 timestamp
	CreatedAfter *string `json:"createdAfter,omitempty"`
	// Filter tenants created before this ISO 8601 timestamp
	CreatedBefore *string `json:"createdBefore,omitempty"`
}

// UserConnection represents a paginated list of users.
type UserConnection struct {
	// List of users in this page
	Items []*user.User `json:"items"`
	// Total count of users matching the filter
	Count int `json:"count"`
}

// UserFilterInput allows filtering users by various criteria.
type UserFilterInput struct {
	// Filter by tenant ID
	TenantID *string `json:"tenantId,omitempty"`
	// Filter by role name
	Role *string `json:"role,omitempty"`
	// Filter by status (active, pending, suspended)
	Status *string `json:"status,omitempty"`
	// Filter users created after this ISO 8601 timestamp
	CreatedAfter *string `json:"createdAfter,omitempty"`
	// Filter users created before this ISO 8601 timestamp
	CreatedBefore *string `json:"createdBefore,omitempty"`
	// Search by email (partial match)
	EmailSearch *string `json:"emailSearch,omitempty"`
}
